# Actividad 1. Minería de datos

Nombre: Juan Sebastian Manrique Moreno

Código: 20202107016

Correo: jsmanriquem@udistrital.edu.co

## Importación de librerías y del archivo .csv

Se importan las librerías `pandas` y `numpy` con sus alias "pd" y "np", respectivamente. Junto a ello, se usa el comando `from google.colab import drive` para importar la unidad de *Google Drive* donde se encuentra el archivo .csv que se va a trabajar.

In [4]:
import pandas as pd
import numpy as np

from google.colab import drive

Se monta la unidad de Google Drive.

In [5]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Se guarda el DataFrame "LISTADO_COLEGIOS_BOGOTA.csv" en su respectivo objeto, llamado `df`.

In [6]:
df = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')

## Ejercicio 1.

Para este ejercicio, se importarán un conjunto de datos con el listado de colegios públicos de Bogotá del año 2016.

In [7]:
print("Las columnas son: ",', '.join(df.columns.tolist()),".",sep="")

Las columnas son: año, secretaria, nombreestablecimiento, zona, direccion, telefono, nombre_Rector, tipo_Establecimiento, etnias, sector, genero, niveles, jornadas, caracter, especialidad, grados, modelos_Educativos, capacidades_Excepcionales, discapacidades, idiomas, numero_de_Sedes, estado, prestador_de_Servicio, propiedad_Planta_Fisica, resguardo, matricula_Contratada, calendario, internado, estrato_Socio_Economico, correo_Electronico.

In [8]:
print("La cantidad de filas es: ",df.shape[0],".",sep="")

La cantidad de filas es: 2404.

In [9]:
df_propiedad_Planta_Fisica = df.query('propiedad_Planta_Fisica == "PERSONA NATURAL" | propiedad_Planta_Fisica == "COMUNIDAD RELIGIOSA"')
print("Los colegios donde la propiedad de la planta física es de una persona natural o de una comunidad religiosa se pueden ver en la siguiente tabla:\n")
df_propiedad_Planta_Fisica

Los colegios donde la propiedad de la planta física es de una persona natural o de una comunidad religiosa se pueden ver en la siguiente tabla:

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

In [10]:
df_capacidades_Excepcionales = df_propiedad_Planta_Fisica['capacidades_Excepcionales'].notna()

if df_capacidades_Excepcionales.any():
    if df_capacidades_Excepcionales.sum() == df_propiedad_Planta_Fisica.shape[0]:
      print("Sí, ¡todos los colegios son para capacidades excepcionales!")
      df_capacidades_Excepcionales = pd.DataFrame()
    else:
      print("Sí, hay un total de",df_capacidades_Excepcionales.sum(),"colegios para capacidades especiales y estos son:\n")
      df_capacidades_Excepcionales = df_propiedad_Planta_Fisica.loc[df_capacidades_Excepcionales,:]
else:
    print("No hay colegios que sean para capacidades excepcionales.")
    df_capacidades_Excepcionales = pd.DataFrame()

pd.set_option('display.max_columns', None)
df_capacidades_Excepcionales if not df_capacidades_Excepcionales.empty else None

Sí, hay un total de 7 colegios para capacidades especiales y estos son:

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,genero,niveles,jornadas,caracter,especialidad,grados,modelos_Educativos,capacidades_Excepcionales,discapacidades,idiomas,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
263,2016,BOGOTA,COL CAMPESTRE MAXIMINO POITIERS ...,URBANA,KR 92 148 51,6835013 / 6841539 ...,KILIAN ALEXANDER ARENAS SANABRIA,INSTITUCION EDUCATIVA,AMORÚA,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,CAPACIDADES EXCEPCIONALES,"DI-COGNITIVO,SÍNDROME DE DOWN",HEBREO,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,kilanarenas@hotmail.com ...
507,2016,BOGOTA,LIC VAL (VIDA-AMOR-LUZ) ...,URBANA,CL 71 C 51 31,2251109 -- 2401331 -- 2502167,LUZ ESPERANZA MORALES SARMIENTO,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,CAPACIDADES EXCEPCIONALES,"TRANSTORNO DEL ESPECTRO AUTISTA,DI-COGNITIVO,P...",NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,liceo.vida.amor.luz.2@gmail.com
1012,2016,BOGOTA,LIC ECOLOGICO DEL NORTE ...,URBANA,CR. 98A NO.156D-26,6822591 / 6839957 ...,JULIA ALICIA PELAEZ CASTILLO,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,CAPACIDADES EXCEPCIONALES,"SORDERA PROFUNDA,MÚLTIPLE DISCAPACIDAD,HIPOACU...",INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,semillasverdes@hotmail.com ...
1367,2016,BOGOTA,GIMNASIO CAMPESTRE STEPHEN HAWKING,URBANA,KR 68 173 A 50,6718575 -- 3005581260,DORA ASTRID PARDO AVILA,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,TALENTO SUBJETIVO/ARTÍSTICO,NaN,NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,SI,A,NaN,NaN,gcstephenhawking@gmail.com
1964,2016,BOGOTA,COL JONATHAN SWIFT ...,URBANA,KR 90 163 30,6818191,DIANA J. MARQUEZ S.,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,CAPACIDADES EXCEPCIONALES,"SV-BAJA VISIÓN,DI-COGNITIVO,SV-CEGUERA,PARALIS...",INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,COLEGIOJONTHANSWIFT@YAHOO.COM.CO ...
2282,2016,BOGOTA,COL CALATRAVA,URBANA,KR 80 156 95,6847860,CONSUELO VALDERRAMA MORALES,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-2,-1,0,1,2,3,4,5,6,7,8,9,10,11","PREESCOLAR ESCOLARIZADO_,EDUCACIÓN TRADICIONAL",TALENTO CIENTIFICO,"TRANSTORNO DEL ESPECTRO AUTISTA,SV-BAJA VISIÓN...",INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,info@colegiocalatrava.edu.co - rectoria@colegi...
2341,2016,BOGOTA,INST DE PEDAG AUTOACTIVA DE GRUPOS (IPAG) ...,URBANA,KR 8 C 183 32,6711029 -- 6701198,CARMEN TULIA CORDOBA ACOSTA,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,"PEDAGOGICO,OTRO,COMERCIAL,ACADÉMICA","0,1,2,3,4,5,6,7,8,9,10,11,14,15",EDUCACIÓN TRADICIONAL,CAPACIDADES EXCEPCIONALES,"DI-COGNITIVO,LESIÓN NEUROMUSCULAR,OTRA DISCAPA...",NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegioipag@gmail.com

In [11]:
df['niveles'] = df['niveles'].astype(str)

# Divide las cadenas en cada celda por comas y cuenta la longitud de la lista resultante
df['max_palabras'] = df['niveles'].str.split(',').apply(len)

# Encuentra la fila con el máximo número de palabras
df_niveles = df[df['max_palabras'] == df['max_palabras'].max()]

print("Los colegios que ofrecen todos los niveles educativos son:\n")
# Imprime la fila con el máximo número de palabras
df_niveles.drop('max_palabras', axis=1)

Los colegios que ofrecen todos los niveles educativos son:

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,genero,niveles,jornadas,caracter,especialidad,grados,modelos_Educativos,capacidades_Excepcionales,discapacidades,idiomas,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",PREESCOLAR NO ESCOLARIZADO/SEMIESCOLARIZADO ...,NaN,NaN,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
1031,2016,BOGOTA,INSTITUTO JUAN PABLO II,URBANA,DG 71 C BIS SUR 77 H 17,7757668,AMPARO BENAVIDES ALBARRACIN,CENTRO EDUCATIVO,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","COMPLETA,FIN DE SEMANA",NaN,ACADÉMICA,"-3,-2,-1,0,1,2,3,4,5,21,22,23,24,25,26","PROGRAMA PARA JÓVENES EN EXTRAEDAD Y ADULTOS,E...",NaN,NaN,NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,institujuan2@hotmail.com
1065,2016,BOGOTA,COLEGIO TOMAS CARRASQUILLA (IED),URBANA,CL 74 A 63 04,6603161 -- 2407959 -- 2400101,ROSA ADELINA RODRIGUEZ RODRIGUEZ,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,ÚNICA,TARDE",NaN,ACADÉMICA,"-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,NaN,NaN,NaN,2,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,colditomascarrasqu12@redp.edu.co
1450,2016,BOGOTA,COLOMBO BRITANICO - BILINGÜE INTERNACIONAL,URBANA,IND AEROPUERTO GUAYMARAL COSTADO SUR OCCIDENTAL,6683999,WALTER ABONDANO MIKAN,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...",COMPLETA,NaN,ACADÉMICA,"-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11",EDUCACIÓN TRADICIONAL,NaN,NaN,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,info@gcb.edu.co -- ruby.gonzalez@gcb.edu.co
2236,2016,BOGOTA,COLEGIO NUEVO HORIZONTE (IED),"RURAL,URBANA",KR 5 B 189 B 30,6793861 - 6796685,HAROLD RODRIGO MURILLO TOVAR,INSTITUCION EDUCATIVA,NaN,NaN,NaN,"PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIM...","MAÑANA,TARDE",NaN,ACADÉMICA,"-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,99","EDUCACIÓN TRADICIONAL,ACELERACIÓN DEL APRENDIZAJE",NaN,"SV-BAJA VISIÓN,DI-COGNITIVO,OTRA DISCAPACIDAD",NaN,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cednvohorizonte1@redp.edu.co

Warning: Total number of columns (30) exceeds max_columns (20) limiting to first (20) columns.

## Ejercicio 2.

In [12]:
import pyeph as pyeph

ModuleNotFoundError: ignored