# **Taller 01. Minería de datos**

Laura Carolina Triana Martínez. 19 de Septiembre

Se tiene como objetivo aplicar los conceptos del preprocesamiento de datos utilizando los portal oficial de datos abiertos de Colombia www.datos.gov.co. Importamos primero las librerías necesarias:

In [1]:
import pandas as pd
import numpy as np
%pip install pyeph
import pyeph

Collecting pyeph
  Downloading pyeph-1.2.0-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 1.9 MB/s eta 0:00:00
Collecting ipykernel<7.0.0,>=6.13.0 (from pyeph)
  Downloading ipykernel-6.25.2-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.2/154.2 kB 7.9 MB/s eta 0:00:00
Requirement already satisfied: openpyxl<4.0.0,>=3.0.10 in /usr/local/lib/python3.10/dist-packages (from pyeph) (3.1.2)
Requirement already satisfied: pandas<2.0.0,>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from pyeph) (1.5.3)
Collecting wget<4.0,>=3.2 (from pyeph)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: xlrd<3.0.0,>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from pyeph) (2.0.1)
Collecting comm>=0.1.1 (from ipykernel<7.0.0,>=6.13.0->pyeph)
  Downloading comm-0.1.4-py3-none-any.whl (6.6 kB)
Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (1.6.6)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (6.1.12)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (5.3.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (0.1.6)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (1.5.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (23.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (5.9.5)
Requirement already satisfied: pyzmq>=20 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (23.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (6.3.2)
Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (5.7.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl<4.0.0,>=3.0.10->pyeph) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.1.5->pyeph) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.1.5->pyeph) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.1.5->pyeph) (1.23.5)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (67.7.2)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph)
  Downloading jedi-0.19.0-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 30.8 MB/s eta 0:00:00
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (4.8.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel<7.0.0,>=6.13.0->pyeph) (3.10.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.1.5->pyeph) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.2.6)
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=6b4f0375d18f720f7bec846e291d440aed1ae7548cac169011935c8e1d38abdc
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget
Installing collected packages: wget, jedi, comm, ipykernel, pyeph
  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 5.5.6
    Uninstalling ipykernel-5.5.6:
      Successfully uninstalled ipykernel-5.5.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipykernel==5.5.6, but you have ipykernel 6.25.2 which is incompatible.
Successfully installed comm-0.1.4 ipykernel-6.25.2 jedi-0.19.0 pyeph-1.2.0 wget-3.2

-----

### **Ejercicio 1: base de datos de colegios de Bogotá**

Se importa una [base de datos](https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD) con el listado de colegios públicos de Bogotá del
año 2016 de www.datos.gov.co, el cual es el portal oficial de datos abiertos de Colombia.

In [2]:
df = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')
df

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

In [3]:
df = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')
df

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

**¿Cuáles son las columnas? ¿Cuántas filas tiene?**

In [4]:
print(f"Los nombres de las {len(df.columns)} columnas son: {', '.join(df.columns)}")

Los nombres de las 30 columnas son: año, secretaria, nombreestablecimiento, zona, direccion, telefono, nombre_Rector, tipo_Establecimiento, etnias, sector, genero, niveles, jornadas, caracter, especialidad, grados, modelos_Educativos, capacidades_Excepcionales, discapacidades, idiomas, numero_de_Sedes, estado, prestador_de_Servicio, propiedad_Planta_Fisica, resguardo, matricula_Contratada, calendario, internado, estrato_Socio_Economico, correo_Electronico

In [5]:
print(f"El DataFrame tiene {df.shape[0]} filas.")

El DataFrame tiene 2404 filas.

**Seleccione los colegios donde la propiedad de la planta física sea de una persona natural o comunidad religiosa.**

In [6]:
df_propiedad = df.query('propiedad_Planta_Fisica == "PERSONA NATURAL" | propiedad_Planta_Fisica == "COMUNIDAD RELIGIOSA"')
print("En la siguiente tabla se observan los colegios donde la propiedad de la planta es de una persona natural o de una comunidad religiosa:\n")
df_propiedad

En la siguiente tabla se observan los colegios donde la propiedad de la planta es de una persona natural o de una comunidad religiosa:

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

**¿Hay alguno de estos colegios que sea para capacidades excepcionales?**

Para poder responder esta pregunta es necesario observar que para la columna de capacidades excepcionales hay valores NaN para indicar que los colegios no son para capacidades excepcionales, por tanto, es necesario filtrar los coelgios que **no** tengan valores nulos, de la siguiente manera:

In [7]:
df_capacidades = df_propiedad.query('capacidades_Excepcionales.notna()')

if not df_capacidades.empty:
    print(f"Sí, hay {len(df_capacidades)} colegios que son para capacidades excepcionales, los cuales se pueden ver a continuación:")
    print(df_capacidades)
else:
    print("No, no hay colegios que sean para capacidades excepcionales.")

Sí, hay 7 colegios que son para capacidades excepcionales, los cuales se pueden ver a continuación:
       año secretaria                              nombreestablecimiento  \
263   2016     BOGOTA  COL CAMPESTRE MAXIMINO POITIERS               ...
507   2016     BOGOTA  LIC VAL (VIDA-AMOR-LUZ)                       ...
1012  2016     BOGOTA  LIC ECOLOGICO DEL NORTE                       ...
1367  2016     BOGOTA                 GIMNASIO CAMPESTRE STEPHEN HAWKING
1964  2016     BOGOTA  COL JONATHAN SWIFT                            ...
2282  2016     BOGOTA                                      COL CALATRAVA
2341  2016     BOGOTA  INST DE PEDAG AUTOACTIVA DE GRUPOS (IPAG)     ...

        zona           direccion  \
263   URBANA        KR 92 148 51
507   URBANA       CL 71 C 51 31
1012  URBANA  CR. 98A NO.156D-26
1367  URBANA      KR 68 173 A 50
1964  URBANA        KR 90 163 30
2282  URBANA        KR 80 156 95
2341  URBANA       KR 8 C 183 32

                                               telefono  \
263   6835013 / 6841539                             ...
507                       2251109 -- 2401331 -- 2502167
1012  6822591 / 6839957                             ...
1367                              6718575 -- 3005581260
1964                                            6818191
2282                                            6847860
2341                                 6711029 -- 6701198

                         nombre_Rector   tipo_Establecimiento  etnias  sector  \
263   KILIAN ALEXANDER ARENAS SANABRIA  INSTITUCION EDUCATIVA  AMORÚA     NaN
507    LUZ ESPERANZA MORALES SARMIENTO  INSTITUCION EDUCATIVA     NaN     NaN
1012      JULIA ALICIA PELAEZ CASTILLO  INSTITUCION EDUCATIVA     NaN     NaN
1367           DORA ASTRID PARDO AVILA  INSTITUCION EDUCATIVA     NaN     NaN
1964              DIANA J.  MARQUEZ S.  INSTITUCION EDUCATIVA     NaN     NaN
2282       CONSUELO VALDERRAMA MORALES  INSTITUCION EDUCATIVA     NaN     NaN
2341       CARMEN TULIA CORDOBA ACOSTA  INSTITUCION EDUCATIVA     NaN     NaN

      ...  numero_de_Sedes estado prestador_de_Servicio  \
263   ...                1    NaN       PERSONA NATURAL
507   ...                1    NaN       PERSONA NATURAL
1012  ...                1    NaN       PERSONA NATURAL
1367  ...                1    NaN       PERSONA NATURAL
1964  ...                1    NaN       PERSONA NATURAL
2282  ...                1    NaN       PERSONA NATURAL
2341  ...                1    NaN       PERSONA NATURAL

      propiedad_Planta_Fisica  resguardo matricula_Contratada calendario  \
263           PERSONA NATURAL  NO APLICA                   NO          A
507           PERSONA NATURAL  NO APLICA                   NO          A
1012          PERSONA NATURAL  NO APLICA                   NO          A
1367          PERSONA NATURAL  NO APLICA                   SI          A
1964          PERSONA NATURAL  NO APLICA                   NO          A
2282          PERSONA NATURAL  NO APLICA                   NO          B
2341          PERSONA NATURAL  NO APLICA                   NO          A

     internado estrato_Socio_Economico  \
263        NaN                     NaN
507        NaN                     NaN
1012       NaN                     NaN
1367       NaN                     NaN
1964       NaN                     NaN
2282       NaN                     NaN
2341       NaN                     NaN

                                     correo_Electronico
263   kilanarenas@hotmail.com                       ...
507                     liceo.vida.amor.luz.2@gmail.com
1012  semillasverdes@hotmail.com                    ...
1367                         gcstephenhawking@gmail.com
1964  COLEGIOJONTHANSWIFT@YAHOO.COM.CO              ...
2282  info@colegiocalatrava.edu.co - rectoria@colegi...
2341                              colegioipag@gmail.com

[7 rows x 30 columns]

**¿Cuáles son los colegios que ofrecen todos los niveles educativos? ¿Qué idiomas ofrecen?**

In [8]:
df_niveles = df.query('niveles == "PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIMARIA,PRIMERA INFANCIA"')
df_niveles

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
1031,2016,BOGOTA,INSTITUTO JUAN PABLO II,URBANA,DG 71 C BIS SUR 77 H 17,7757668,AMPARO BENAVIDES ALBARRACIN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,institujuan2@hotmail.com
1065,2016,BOGOTA,COLEGIO TOMAS CARRASQUILLA (IED),URBANA,CL 74 A 63 04,6603161 -- 2407959 -- 2400101,ROSA ADELINA RODRIGUEZ RODRIGUEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,2,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,colditomascarrasqu12@redp.edu.co
1450,2016,BOGOTA,COLOMBO BRITANICO - BILINGÜE INTERNACIONAL,URBANA,IND AEROPUERTO GUAYMARAL COSTADO SUR OCCIDENTAL,6683999,WALTER ABONDANO MIKAN,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,info@gcb.edu.co -- ruby.gonzalez@gcb.edu.co
2236,2016,BOGOTA,COLEGIO NUEVO HORIZONTE (IED),"RURAL,URBANA",KR 5 B 189 B 30,6793861 - 6796685,HAROLD RODRIGO MURILLO TOVAR,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cednvohorizonte1@redp.edu.co

In [9]:
df_idiomas = df_niveles['idiomas']
df_idiomas

5       INGLÉS
1031       NaN
1065       NaN
1450    INGLÉS
2236       NaN
Name: idiomas, dtype: object

## **Ejercicio 2**

Seleccione el 2do trimestre del 2021 mediante el comando: eph = pyeph.get(data="eph", year=2021, period=2, base_type='individual')

In [10]:
eph = pyeph.get(data="eph", year=2021, period=2, base_type='individual')
eph

Obtenido con exito: base_individual_2021T2.zip

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,PDECIFR,ADECIFR,IPCF,DECCFR,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH
0,TQRMNOPYQHMLKNCDEHJGH00699689,2021,2,1,1,1,40,S,23,214,...,NaN,5,27000,6,7.0,8,6.0,NaN,8,218
1,TQRMNOPYQHMLKNCDEHJGH00699689,2021,2,1,2,1,40,S,23,214,...,NaN,5,27000,6,7.0,8,6.0,NaN,8,218
2,TQRMNOPYSHMLKNCDEHJGH00699098,2021,2,1,1,1,40,S,23,192,...,NaN,10,46000,9,9.0,10,8.0,NaN,9,196
3,TQRMNOPYSHMLKNCDEHJGH00699098,2021,2,1,2,1,40,S,23,192,...,NaN,10,46000,9,9.0,10,8.0,NaN,9,196
4,TQRMNOPYSHMLKNCDEHJGH00699098,2021,2,1,3,1,40,S,23,192,...,NaN,10,46000,9,9.0,10,8.0,NaN,9,196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47080,TQRMNOQWSHLLKUCDEOJAH00708363,2021,2,1,1,1,44,N,93,86,...,12.0,12,0,12,12.0,12,0.0,12.0,12,0
47081,TQRMNOQWSHLLKUCDEOJAH00708363,2021,2,1,2,1,44,N,93,86,...,12.0,12,0,12,12.0,12,0.0,12.0,12,0
47082,TQRMNOSRVHLOLRCDEHJGH00708364,2021,2,1,1,1,40,S,23,230,...,NaN,4,8400,2,2.0,2,2.0,NaN,2,228
47083,TQRMNOSRVHLOLRCDEHJGH00708364,2021,2,1,2,1,40,S,23,230,...,NaN,4,8400,2,2.0,2,2.0,NaN,2,228
47084,TQRMNOSRVHLOLRCDEHJGH00708364,2021,2,1,3,1,40,S,23,230,...,NaN,4,8400,2,2.0,2,2.0,NaN,2,228

Identifique cuales son las columnas del dataset.

In [11]:
eph.columns

Index(['CODUSU', 'ANO4', 'TRIMESTRE', 'NRO_HOGAR', 'COMPONENTE', 'H15',
       'REGION', 'MAS_500', 'AGLOMERADO', 'PONDERA',
       ...
       'PDECIFR', 'ADECIFR', 'IPCF', 'DECCFR', 'IDECCFR', 'RDECCFR', 'GDECCFR',
       'PDECCFR', 'ADECCFR', 'PONDIH'],
      dtype='object', length=177)

Cree una variable llamada eph_2 que contenga las siguientes columnas para realizar el siguiente análisis:

In [12]:
eph_2 = eph.loc[:,['CH06', 'CH04', 'P21', 'CAT_OCUP', 'ESTADO', 'PONDERA']]
eph_2

       CH06  CH04    P21  CAT_OCUP  ESTADO  PONDERA
0        58     1  50000         2       1      214
1        24     1      0         3       2      214
2        51     2      0         4       1      192
3        27     1   4000         2       1      192
4        18     1      0         0       3      192
...     ...   ...    ...       ...     ...      ...
47080    77     2      0         0       3       86
47081    57     1     -9         2       1       86
47082    73     2      0         0       3      230
47083    44     2  18000         3       1      230
47084    20     1   4000         2       1      230

[47085 rows x 6 columns]

Traer un dataframe que filtre solo a las personas que tengan 21 años o menos.

In [13]:
menores_de_21 = eph_2.query('CH06 <= 21')
menores_de_21

       CH06  CH04   P21  CAT_OCUP  ESTADO  PONDERA
4        18     1     0         0       3      192
8         5     1     0         0       4      250
11       19     2     0         0       3      250
12       17     1     0         0       3      250
13       14     1     0         0       3      250
...     ...   ...   ...       ...     ...      ...
47070    15     2     0         0       3       46
47071    13     1     0         0       3       46
47074     8     1     0         0       4       49
47077    10     1     0         0       3      111
47084    20     1  4000         2       1      230

[15192 rows x 6 columns]

Traer un dataframe que filtre a las personas desocupadas de más de 40 años.

In [14]:
mas_de_40 = eph_2.query('CH06 > 40 & ESTADO == 2')
mas_de_40

       CH06  CH04  P21  CAT_OCUP  ESTADO  PONDERA
47       58     2    0         3       2      915
77       41     1    0         2       2      139
92       45     1    0         3       2      127
357      42     1    0         3       2     1086
433      48     2    0         3       2      626
...     ...   ...  ...       ...     ...      ...
46276    54     1    0         2       2      593
46350    49     1    0         3       2      307
46447    72     1    0         2       2      232
46599    49     2    0         3       2      311
46715    49     2    0         3       2      215

[503 rows x 6 columns]

¿Cuántas mujeres hay en la base de datos? ¿Y hombres?

In [15]:
mujeres = eph_2.query('CH04 == 1')
mujeres.shape[0]

22602

In [16]:
hombres = eph_2.query('CH04 == 2')
hombres.shape[0]

24483

¿Cuál era la tasa de desocupación en el período seleccionado para las mujeres? ¿Era más alta o más baja que la de los hombres?

In [17]:
eph_ocupadas = mujeres.query('ESTADO == 1')
eph_desocupadas = mujeres.query('ESTADO == 2')

tasa = eph_ocupadas.shape[0]/(eph_ocupadas.shape[0]+eph_desocupadas.shape[0])
print(tasa)

0.9252075215991868

In [18]:
eph_ocupados = hombres.query('ESTADO == 1')
eph_desocupados = hombres.query('ESTADO == 2')

tasa = eph_ocupados.shape[0]/(eph_ocupados.shape[0]+eph_desocupados.shape[0])
print(tasa)

0.9085555198629404

In [19]:
def calcular_tasa_ocupacion(data):
    eph_ocupados = data.query('ESTADO == 1')
    eph_desocupados = data.query('ESTADO == 2')

    tasa_ocupacion = eph_ocupados.shape[0] / (eph_ocupados.shape[0] + eph_desocupados.shape[0])
    return tasa_ocupacion

tasa = calcular_tasa_ocupacion(mujeres)
print(tasa)
tasah = calcular_tasa_ocupacion(hombres)
print(tasah)

0.9252075215991868
0.9085555198629404