# **Exploración**

Vamos a analizar datos de una fuente real. Los ingresos de los funcionarios son información pública que se libera anualmente en el <a href='https://data.buenosaires.gob.ar/dataset/sueldo-funcionarios'>portal de datos abiertos</a> de GCBA.  

En general los 4 primeros pasos para analizar un data set son:
1. Leerlo
2. Consultar cuáles son las columnas
3. Extraer una muestra
4. Verificar cuántos registros tiene

## **Lectura de Data Set**

Con la función `pd.read_csv()` podemos leer archivos que estén en una url pública o en una ubicación del disco accesible desde la Jupyter Notebook.

In [1]:
import pandas as pd
import numpy as np
import time

df = pd.read_csv('http://cdn.buenosaires.gob.ar/datosabiertos/datasets/sueldo-funcionarios/sueldo_funcionarios_2019.csv')
df

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.00,197745.80,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.00,197745.80,NaN
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.00,224516.62,NaN
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.00,224516.62,NaN
...,...,...,...,...,...,...,...,...,...,...
380,20-26735689-1,2019,12,MENDEZ,JUAN JOSE,SECR Transporte y Obras Públicas,249972.86,124986.43,374959.29,NaN
381,20-23864572-8,2019,12,STRAFACE,FERNANDO DIEGO,SECR General y Relaciones Internacionales,275089.75,137544.87,412634.62,NaN
382,20-21981279-6,2019,12,SCRENCI SILVA,BRUNO GUIDO,Ministerio de Gobierno,275089.75,137544.87,412634.62,NaN
383,20-30593774-7,2019,12,AVELLANEDA,PATRICIO IGNACIO,"SECR Planificación, Evaluación y Coordinación ...",249972.86,124986.43,374959.29,NaN
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

In [2]:
df.columns

Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')

In [3]:
df.sample(5)  #Selecciona una muestra de registros aletoria

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
364,20-29751476-9,2019,12,CARRILLO,FACUNDO,SECR Atención Ciudadana y Gestión Comunal,249972.86,124986.43,374959.29,NaN
83,20-24424714-9,2019,3,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,210061.14,0.00,210061.14,NaN
39,20-17110752-1,2019,2,MACCHIAVELLI,EDUARDO ALBERTO,Ministerio de Ambiente y Espacio Público,224516.62,0.00,224516.62,NaN
183,20-16891539-0,2019,6,ROBREDO,GONZALO,Ente de Turismo Ley Nº 2627,226866.41,113433.21,340299.62,NaN
179,20-20008464-1,2019,6,GIUSTI,JOSE LUIS,UPE Transferencia de Funciones y Facultades en...,226866.41,113433.21,340299.62,NaN

In [4]:
# La propiedad shape nos devuelve una tupla (filas,columnas)
df.shape

(385, 10)

# **Vectorización con Pandas**

Pandas es una de las librerías de Python más usadas para análisis de datos. El nombre pandas viene de "Panel Data Analysis" y su funcionalidad permite hacer operaciones sobre datos que se encuentran en memoria de manera eficiente.

Pandas es útil para trabajar sobre datos tabulares, con dos condiciones importantes:

I. Los datos se encuentran enteramente en la memoria RAM. Con lo cual, el tamaño de los datos que podemos manipular está limitado por el hardware. Como regla de pulgar, es una buena práctica no ocupar más de 1/3 de la memoria RAM de nuestro dispositivo con el dataset. Así, si estamos trabajando localmente en una notebook con 8GB de memoria RAM no es recomendable procesar datasets de más de 2.33GB.

II. En pandas, las operaciones sobre filas y columnas son, en general, eficientes porque se hacen de forma "vectorizada". En realidad esta optimización, se hace desde numpy, una librería para realizar operaciones matemáticas que se utilizó a su vez para escribir pandas.

Las operaciones vectorizadas son las que se realizan en bloque en vez de caso por caso. Las computadoras de hoy tienen la capacidad de recibir muchas instrucciones juntas y procesar varias de ellas a la vez.

Es importante entender que Pandas trabaja de esta manera y que por eso es una de las herramientas más elegidas para manipular datos en memoria.

In [5]:
#Ejemplo de Vectorización (Muchos datos al mismo tiempo)
#para saber cuando se demora el calculo
%timeit
df["bonificacion"]=df["asignacion_por_cargo_i"]*0.
df.head()

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones,bonificacion
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.0,197745.80,NaN,0.0
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.0,197745.80,NaN,0.0
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.0,224516.62,NaN,0.0
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN,0.0
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN,0.0

# **Objetos fundamentales de Pandas**

## **Series**

Las series son "columnas" que de una tabla que están asociadas a un índice y a un nombre. Igual que una lista común de Python es una secuencia de elementos ordenados, pero a diferencia de la lista está asociada a más información.

In [6]:
# Las series se pueden crear a partir de una lista
serie = pd.Series(['a','b','c'])

In [7]:
# Propiedades importantes de las series
print('Tipo de objetos que tiene ', serie.dtype)
print('Nombre ', serie.name)
print('Index ',serie.index)
print('Valores ',serie.values)

Tipo de objetos que tiene  object
Nombre  None
Index  RangeIndex(start=0, stop=3, step=1)
Valores  ['a' 'b' 'c']

## **DataFrames**

Los DataFrames son "tablas", compuestas por varias "columnas" o series que comparten todas un mismo índice. En general los DataFrames se crean a partir de leer tablas de archivos (pueden ser en formato json o csv) pero a veces también se crean a partir de listas de diccionarios o de otras maneras.

Los DataFrames tienen un objeto Index que describe los nombres de columnas y otro objeto Index que describen los nombres de las filas.

In [8]:
# Leemos un dataset público
df = pd.read_csv('http://cdn.buenosaires.gob.ar/datosabiertos/datasets/sueldo-funcionarios/sueldo_funcionarios_2019.csv')

In [9]:
# Propiedades importantes de los dataframes
print('Columnas ', df.columns)
print('Index ', df.index)
print('Dimensiones ',df.shape)

Columnas  Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')
Index  RangeIndex(start=0, stop=385, step=1)
Dimensiones  (385, 10)

In [10]:
# Consultar las primeras filas
df.head()

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.0,197745.80,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.0,197745.80,NaN
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.0,224516.62,NaN
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN

Si queremos extraer una serie del DataFrame, podemos hacerlo de la misma forma en que extraemos un valor de un diccionario.

In [11]:
serie_mes = df['mes']

In [12]:
type(serie_mes) #tipo de dato que se esta
serie_mes

0       1
1       1
2       1
3       1
4       1
       ..
380    12
381    12
382    12
383    12
384    12
Name: mes, Length: 385, dtype: int64

## **Índices**

Los índices acompañan a las series y a los Data Frames. Son conjuntos ordenados e inmutables de elementos

In [13]:
df.index

RangeIndex(start=0, stop=385, step=1)

In [14]:
df.columns

Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')

In [15]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### **Ejercicio**
Exploren el dataset público que se encuentra en la siguiente url: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv ¿De qué se trata? ¿Cuántas filas tiene? ¿Cuántas columnas? Al leerlo, pueden almacenarlo en la variable df_titanic.

In [16]:
df_titanic = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv',sep=",")

In [17]:
df_titanic.describe()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,887.000000,887.000000,887.000000,887.000000,887.000000,887.00000
mean,0.385569,2.305524,29.471443,0.525366,0.383315,32.30542
std,0.487004,0.836662,14.121908,1.104669,0.807466,49.78204
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.00000
25%,0.000000,2.000000,20.250000,0.000000,0.000000,7.92500
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.45420
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.13750
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.32920

In [18]:
df_titanic.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [19]:
df_titanic.shape

(887, 8)

## **Filtrando un DataFrame (Indexing)**

Hay muchas técnicas para filtrar un DataFrame. Podemos querer filtrar por columnas o por filas, por posición o por nombre. También podemos querer filtrar por condiciones que se cumplen o no. Cuando no queremos filtrar sobre una dimensión (filas o columnas) usamos ":" para seleccionar todo.

### **Boolean Indexing**

Supongamos que queremos tomar el dataset de funcionarios y quedarnos únicamente con los que pertenecen al Ministerio de Cultura.
Para eso lo que hacemos es indexar al DataFrame por una condición booleana. Eso implica que debemos crear una serie compuesta por valores True y False para aplicarla como índice a las filas.

Los operadores que sirven para evaluar condiciones sobre las series son:


| S  | Descripción   | S  | Descripción   |   |
|----|---------------|----|---------------|---|
| >= | Mayor o Igual | <= | Menor o Igual |   |
| == | Igual         | != | Distinto      |   |
| >  | Mayor         | <  | Menor         |   |

### **Máscara booleana**

Veamos lo que pasa cuando le aplicamos a una serie una condición que devuelve un booleano

In [20]:
mascara_booleana = df['anio'] != 2019
mascara_booleana

0      False
1      False
2      False
3      False
4      False
       ...
380    False
381    False
382    False
383    False
384    False
Name: anio, Length: 385, dtype: bool

Nos devuelve una serie de la misma longitud que la original y que contiene sólo valores True o False.

In [21]:
type(mascara_booleana)

pandas.core.series.Series

In [22]:
mascara_booleana.shape

(385,)

In [23]:
mascara_booleana.dtype

dtype('bool')

Ahora seleccionemos entonces, los registros que corresponden al Ministerio de Cultura.

In [24]:
df_min_cul = df.loc[df['reparticion'] == 'Ministerio de Cultura',:]
df_min_cul.head()

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN
36,20-25641207-2,2019,2,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.0,224516.62,NaN
68,20-25641207-2,2019,3,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,231167.76,0.0,231167.76,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.0,249661.60,NaN
130,20-25641207-2,2019,5,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.0,249661.60,NaN

In [25]:
# Veamos la cantidad de casos
df_min_cul.shape

(12, 10)

### **Ejercicio**

Traer todos los sueldos de la segunda mitad del año...

In [26]:
df_mitaddos = df[df['mes'] >=7]
df_mitaddos

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
188,20-17692128-6,2019,7,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,228396.40,0.00,228396.40,NaN
189,20-17735449-0,2019,7,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,228396.40,0.00,228396.40,NaN
190,27-24483014-0,2019,7,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,263531.98,0.00,263531.98,NaN
191,20-13872301-2,2019,7,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
192,20-25641207-2,2019,7,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,263531.98,0.00,263531.98,NaN
...,...,...,...,...,...,...,...,...,...,...
380,20-26735689-1,2019,12,MENDEZ,JUAN JOSE,SECR Transporte y Obras Públicas,249972.86,124986.43,374959.29,NaN
381,20-23864572-8,2019,12,STRAFACE,FERNANDO DIEGO,SECR General y Relaciones Internacionales,275089.75,137544.87,412634.62,NaN
382,20-21981279-6,2019,12,SCRENCI SILVA,BRUNO GUIDO,Ministerio de Gobierno,275089.75,137544.87,412634.62,NaN
383,20-30593774-7,2019,12,AVELLANEDA,PATRICIO IGNACIO,"SECR Planificación, Evaluación y Coordinación ...",249972.86,124986.43,374959.29,NaN
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

In [27]:
df_mitaddos.shape

(197, 10)

### **Ejercicio**
Volviendo al DataFrame del Titanic ¿Cuántos pasajeros sobrevivieron y cuántos no? ¿Cuántos pagaron una tarifa menor a 25?

In [28]:
df_titanic_sob=df_titanic.loc[df_titanic["Survived"] == 1,:]

In [29]:
df_titanic_sob.shape

(342, 8)

In [30]:
df_titanic_nosob=df_titanic.loc[df_titanic["Survived"] == 0,:]

In [31]:
df_titanic_nosob.shape

(545, 8)

### **Máscara booleana con muchas condiciones**

Ahora tratemos de filtrar el dataset por dos condiciones: por ejemplo tomar los sueldos de abril de la secretaria de innovación.
Para eso tenemos que combinar dos máscaras booleanas con una condición.

| S | Descripcion        | S  | Descripcion |   |
|---|--------------------|----|-------------|---|
| & | AND (y)            | \| | OR (o)      |   |
| ^ | XOR (o exclusivo)  | ~  | NOT (no)    |   |



Por ejemplo: seleccionemos los casos donde o bien se haya cobrado aguinaldo o bien el salario total haya sido mayor que 240.000, pero no las dos cosas.

In [32]:
df[(df['total_salario_bruto_i_+_ii'] > 240000) ^ (df['aguinaldo_ii'] > 0)]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019
97,27-24483014-0,2019,4,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,249661.60,0.00,249661.60,NaN
98,20-13872301-2,2019,4,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.00,249661.60,NaN
100,27-13221055-7,2019,4,BOU PEREZ,ANA MARIA,Ministerio de Salud,249661.60,0.00,249661.60,NaN
...,...,...,...,...,...,...,...,...,...,...
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
361,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SECR de Medios,187539.45,15628.29,203167.74,alta desde el 10/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12
363,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,187539.45,15628.29,203167.74,alta desde el 10/12
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

Ahora veamos los sueldos de febrero de la SECR Ciencia, Tecnologia e Innovacion.

In [33]:
df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019

## **Boolean indexing con query()**

La sintaxis que se utiliza para hacer Boolean indexing es un poco repetitiva. Noten que filtrar (aún en su expresión más corta sin loc ni especificar filas o columnas) implica ESCRIBIR DOS VECES el nombre del dataset. Para crear un shortcut, Pandas ofrece la función .query()

In [34]:
df_cult = df.query('reparticion == "Ministerio de Cultura"')

También se puede hacer query sobre múltiples condiciones.

In [35]:
df2 = df.query('asignacion_por_cargo_i > 240000 & aguinaldo_ii > 0')

In [36]:
df2.shape

(34, 10)

### **Ejercicio**
Piensen cómo traducir a la sintaxis de query, estas consultas que ya hicimos

In [37]:
# df_sem2 = df[df['mes'] > 6]
df_sem2 =df.query('mes > 6')
df_sem2.shape

(197, 10)

In [38]:
# df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]
df5= df.query('mes == 2 & reparticion == "SECR Ciencia, Tecnologia e Innovacion"')
df5.shape

(1, 10)

## **Fancy Indexing**

Ahora vamos a quedarnos con un subconjunto de columnas del DataFrame.

In [39]:
df_view = df.loc[:,['anio','mes']]

In [40]:
df_view.shape

(385, 2)

In [41]:
df_view

     anio  mes
0    2019    1
1    2019    1
2    2019    1
3    2019    1
4    2019    1
..    ...  ...
380  2019   12
381  2019   12
382  2019   12
383  2019   12
384  2019   12

[385 rows x 2 columns]

Existe una forma menos explícita de hacer esta misma operación. Si pasamos una lista al indexing, pandas asume que el tipo de indexing es loc y que el filtro es sobre las columnas y no las filas:

In [42]:
df_view = df[['anio','mes']]

In [43]:
df_view.shape

(385, 2)

Fíjense lo que pasa si tratamos de acceder a filas utilizando una lista de nombres, en este caso [0,1].

In [44]:
# Incorrecto
df_view = df[[3,8]]

KeyError: "None of [Index([3, 8], dtype='int64')] are in the [columns]"

Nos da un error porque cuando pasamos únicamente una lista al indexing, pandas asume que queremos un set de columnas y si los nombres no existen, da error. La forma correcta de hacerlo es pasar una lista de índices y explicitar que vamos a indizar con loc y que seleccionamos todas las columnas.

In [45]:
# Correcto
df_view = df.loc[[3,8],:]

In [46]:
df_view

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN
8,20-22293873-3,2019,1,MIGUEL,FELIPE OSCAR,Jefatura de Gabinete de Ministros,224516.62,0.0,224516.62,NaN

## **Ejercicio**
Para el Data Set de Titanic

1) ¿Cuántos hombres y mujeres sobrevivieron?

2) ¿Cuántos menores de 18 años había? ¿Cuántos sobrevivieron?

3) Seleccionen únicamente las columnas Sex y Survived y almacenenlas en un nuevo DataFrame que se llame df_titanic_subset.

In [47]:
# Agrupamos por sexo y condición de supervivencia
survivors_by_sex = df_titanic.groupby(["Sex", "Survived"]).size().unstack()
print(survivors_by_sex)

Survived    0    1
Sex
female     81  233
male      464  109

In [48]:
# Filtramos los menores de 18 años
menores = df_titanic[df_titanic["Age"] < 18]

# Total de menores
total_menores = len(menores)

# Menores que sobrevivieron
menores_sobrevivieron = menores["Survived"].sum()  # porque Survived es 0 o 1

print("Total de menores de 18:", total_menores)
print("Menores que sobrevivieron:", menores_sobrevivieron)

Total de menores de 18: 130
Menores que sobrevivieron: 65

In [49]:
df_titanic_subset = df_titanic[["Sex", "Survived"]]
print(df_titanic_subset.head())

      Sex  Survived
0    male         0
1  female         1
2  female         1
3  female         1
4    male         0

# **Funciones de Agregación**

Utilizando Pandas podemos aplicar funciones a nivel de columna. Algunas funciones predefinidas son la media, el desvío estándar y la sumatoria, el valor máximo y el mínimo.

Algunas de las funciones de agregación más comunes son:

<ul>
    <li>min</li>
    <li>max</li>
    <li>count</li>
    <li>sum</li>
    <li>prod</li>
    <li>mean</li>
    <li>median</li>
    <li>mode</li>
    <li>std</li>
    <li>var</li>
</ul>

In [50]:
df['mes'].max()

np.int64(12)

In [51]:
df['asignacion_por_cargo_i'].mean()

np.float64(234234.36800000002)

In [52]:
df['asignacion_por_cargo_i'].std()

np.float64(35043.160084661766)

In [53]:
df['total_salario_bruto_i_+_ii'].sum()

np.float64(97988834.36000001)

Podemos combinar los filtros que vimos antes con las funciones de agregación para responder preguntas cómo ¿Cuál fue en gasto en asignaciones de funcionarios para la Secretaría de Medios 2019? ¿Y para la de Justicia y Seguridad?

In [54]:
df[df['reparticion'] == 'SECR de Medios']['total_salario_bruto_i_+_ii'].sum()

np.float64(3232402.25)

In [55]:
df[df['reparticion'] == 'SECR Justicia y Seguridad']['total_salario_bruto_i_+_ii'].sum()

np.float64(3029551.7300000004)

Ahora respondamos algunas preguntas: ¿Quién o quiénes del dataset cobran el salario más alto? ¿Y el más bajo?

In [56]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].max()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [57]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].min()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
344,27-30744939-6,2019,12,FERRERO,GENOVEVA,SECR Administración de Seguridad y Emergencias,74991.86,110404.68,185396.54,baja al 9/12
348,20-22709722-2,2019,12,LOPEZ,MATIAS,SECR Desarrollo Ciudadano,74991.86,110404.68,185396.54,baja al 9/12
354,20-20008464-1,2019,12,GIUSTI,JOSE LUIS,UPE Transferencia de Funciones y Facultades en...,74991.86,110404.68,185396.54,baja al 9/12
358,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,SS Comunicacion,74991.86,110404.68,185396.54,baja al 9/12
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12

## **Análisis para variables numéricas**

Pandas viene con algunas funciones built-in para ayudar al análisis descriptivo.

In [58]:
df.describe()

,anio,mes,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii
count,385.0,385.000000,385.000000,385.000000,385.000000
mean,2019.0,6.631169,234234.368000,20282.084883,254516.452883
std,0.0,3.539077,35043.160085,45248.840725,51434.987870
min,2019.0,1.000000,74991.860000,0.000000,185396.540000
25%,2019.0,4.000000,224516.620000,0.000000,224516.620000
50%,2019.0,7.000000,239470.360000,0.000000,245811.620000
75%,2019.0,10.000000,249972.870000,0.000000,263531.980000
max,2019.0,12.000000,275089.750000,170855.560000,445945.310000

## **Análisis para variables categóricas**

In [59]:
df['reparticion'].value_counts()

reparticion
SECR Desarrollo Ciudadano                                         13
Ministerio de Salud                                               13
SECR Justicia y Seguridad                                         13
SECR de Medios                                                    13
Jefe de Gobierno                                                  12
SECR Legal y Técnica                                              12
SS Contenidos                                                     12
Ente de Turismo Ley Nº 2627                                       12
Consejo de los Derechos de Niñas, Niños y Adoles - Presidencia    12
Vicejefatura de Gobierno                                          12
UPE Transferencia de Funciones y Facultades en Materia de Seg.    12
SECR Administración de Seguridad y Emergencias                    12
SECR Integración Social y Urbana                                  12
SECR Integración Social Para Personas Mayores                     12
SECR Planificación, Evaluación y Coordinación de Gestión          12
SS Comunicacion                                                   12
Ministerio de Gobierno                                            12
Ministerio de Desarrollo Urbano y Transporte                      12
Jefatura de Gabinete de Ministros                                 12
Procuración General de la Ciudad de Buenos Aires                  12
Sindicatura General de la Ciudad de Buenos Aires                  12
Ministerio de Cultura                                             12
SECR Transporte                                                   11
Ministerio de Educación e Innovación                              11
SECR Coordinación General                                         11
SECR Cultura Ciudadana y Función Pública                          11
SECR General y de Relaciones Internacionales                      11
Ministerio de Economía y Finanzas                                 11
Ministerio de Hábitat y Desarrollo Humano                         11
SECR Atención y Gestión Ciudadana                                 11
Ministerio de Ambiente y Espacio Público                          11
Ministerio de Espacio Público e Higiene Urbana                     2
SECR Ciencia, Tecnologia e Innovacion                              2
Ministerio de Desarrollo Humano y Hábitat                          2
SECR Desarrollo Urbano                                             1
Ministerio de Desarrollo Económico y Producción                    1
SECR Ambiente                                                      1
SECR Comunicación, Contenidos y Participación Ciudadana            1
SECR Atención Ciudadana y Gestión Comunal                          1
Ministerio de Educación                                            1
Ministerio de Hacienda y Finanzas                                  1
SECR Innovación y Transformación Digital                           1
SECR Transformación Cultural                                       1
SECR Transporte y Obras Públicas                                   1
SECR General y Relaciones Internacionales                          1
SECR Asuntos Estratégicos                                          1
Name: count, dtype: int64

## **Ejercicio** 

Volviendo al ejemplo del Titanic:

1) ¿Cuál era la edad promedio de los pasajeros de cada clase (Pclass)?

2) ¿Cuál fue la tarifa que pagaron en promedio los hombres? ¿Y las mujeres?

3) ¿Cuánto pagaron en total los pasajeros de primera clase para subir al Titanic? ¿Y los de tercera?

4) ¿Cuántos pasajeros había en cada tipo de clase?

In [60]:
# 1) Edad promedio de los pasajeros por clase (Pclass)
edad_promedio_clase = df_titanic.groupby("Pclass")["Age"].mean()
print("Edad promedio por clase:")
print(edad_promedio_clase)

Edad promedio por clase:
Pclass
1    38.788981
2    29.868641
3    25.188747
Name: Age, dtype: float64

In [61]:
# 2) Tarifa promedio por sexo
tarifa_promedio_sexo = df_titanic.groupby("Sex")["Fare"].mean()
print("\nTarifa promedio por sexo:")
print(tarifa_promedio_sexo)

Tarifa promedio por sexo:
Sex
female    44.479818
male      25.633935
Name: Fare, dtype: float64

In [62]:
# 3) Total pagado por pasajeros de 1ra y 3ra clase
total_tarifa_clase = df_titanic.groupby("Pclass")["Fare"].sum()
print("\nTotal pagado por clase:")
print(total_tarifa_clase.loc[[1, 3]])  # solo primera y tercera clase

Total pagado por clase:
Pclass
1    18177.4125
3     6675.6535
Name: Fare, dtype: float64

In [63]:

# 4) Número de pasajeros en cada clase
pasajeros_por_clase = df_titanic["Pclass"].value_counts().sort_index()
print("\nPasajeros por clase:")
print(pasajeros_por_clase)

Pasajeros por clase:
Pclass
1    216
2    184
3    487
Name: count, dtype: int64

## **Ordenar por columnas y limitar la cantidad de resultados**

Otra forma de resolver el problema de encontrar el mayor y el menos es con el método sort_values. Este método puede recibir un valor único (nombre de columna) o una lista (con varias columnas) y un orden asc o desc. Por default el orden es asc.

Si combinamos el ordenamiento con el método head() para limitar la cantidad de resultados, podemos encontrar los N primeros.

In [65]:
# Recordemos cómo abrir la documentación de un método
df.sort_values

<bound method DataFrame.sort_values of               cuil  anio  mes funcionario_apellido funcionario_nombre  \
0    20-17692128-6  2019    1    RODRIGUEZ LARRETA    HORACIO ANTONIO
1    20-17735449-0  2019    1             SANTILLI        DIEGO CESAR
2    27-24483014-0  2019    1                ACUÑA      MARIA SOLEDAD
3    20-13872301-2  2019    1             ASTARLOA      GABRIEL MARIA
4    20-25641207-2  2019    1             AVOGADRO       ENRIQUE LUIS
..             ...   ...  ...                  ...                ...
380  20-26735689-1  2019   12               MENDEZ          JUAN JOSE
381  20-23864572-8  2019   12             STRAFACE     FERNANDO DIEGO
382  20-21981279-6  2019   12        SCRENCI SILVA        BRUNO GUIDO
383  20-30593774-7  2019   12           AVELLANEDA   PATRICIO IGNACIO
384  27-27011181-0  2019   12            FERNANDEZ     KARINA BEATRIZ

                                           reparticion  \
0                                     Jefe de Gobierno
1                             Vicejefatura de Gobierno
2                 Ministerio de Educación e Innovación
3     Procuración General de la Ciudad de Buenos Aires
4                                Ministerio de Cultura
..                                                 ...
380                   SECR Transporte y Obras Públicas
381          SECR General y Relaciones Internacionales
382                             Ministerio de Gobierno
383  SECR Planificación, Evaluación y Coordinación ...
384                          SECR Asuntos Estratégicos

     asignacion_por_cargo_i  aguinaldo_ii  total_salario_bruto_i_+_ii  \
0                 197745.80          0.00                   197745.80
1                 197745.80          0.00                   197745.80
2                 224516.62          0.00                   224516.62
3                 224516.62          0.00                   224516.62
4                 224516.62          0.00                   224516.62
..                      ...           ...                         ...
380               249972.86     124986.43                   374959.29
381               275089.75     137544.87                   412634.62
382               275089.75     137544.87                   412634.62
383               249972.86     124986.43                   374959.29
384               187539.45      15628.29                   203167.74

           observaciones
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
..                   ...
380                  NaN
381                  NaN
382                  NaN
383                  NaN
384  alta desde el 10/12

[385 rows x 10 columns]>

In [66]:
# Calculamos el máximo
df.sort_values('total_salario_bruto_i_+_ii',ascending=False).head(1)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [67]:
# Calculamos el mínimo
df.sort_values('total_salario_bruto_i_+_ii').head(1)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
344,27-30744939-6,2019,12,FERRERO,GENOVEVA,SECR Administración de Seguridad y Emergencias,74991.86,110404.68,185396.54,baja al 9/12

# **Anexo: Vectorización**

¿Por qué es tan importante trabajar con Pandas y no con funciones escritas por nosotros en Python nativo y que procesen los datos dentro de un for loop?

Por un lado está la comodidad. Hay mucha funcionalidad que ya está desarrollada en Pandas. Existen funciones que resuelven muchos de los problemas clásicos de manipular datos: agrupar, sumarizar, sacar estadísticas, filtrar, etc. Pero además hay una razón de performance.

Veamos una demostración de que vectorizar es más eficiente. Vamos a crear dos listas de 1.000.000 de números aleatorios cada una y vamos a tratar de multiplicar elemento por elemento con pandas y sin pandas:

In [68]:
lista1 = list(np.random.randint(1, 100, 1000000))
lista2 = list(np.random.randint(1, 100, 1000000))

In [69]:
%%timeit
for x,y in zip(lista1,lista2):
    x * y

97.6 ms ± 2.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Ahora probemos hacer lo mismo con dos series de Pandas

In [70]:
serie1 = pd.Series(lista1)
serie2 = pd.Series(lista2)

In [71]:
%%timeit
resultado = serie1 * serie2
print(resultado)

0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960
1          979
2          884
3         4508
4          992
          ...
999995    1638
999996    2272
999997    9207
999998     910
999999    4200
Length: 1000000, dtype: int64
0          960

Conclusión: la operación vectorizada es <strong> más de 70 veces más rápida.</strong>